# Layer definitions
layers:
  me_wic_farmstands:
    title: "Maine WIC Farmstands"
    file: "data/ME_WIC_Farmstands_wgs.geojson"
    type: "point"
    style:
      color: "#ff7800"
      radius: 4

  //new_england_shelters:
    //title: "New England Shelters"
    //file: "data/New_England_shelters.geojson"
    //type: "point"
    //style:
      //color: "#2ca25f"
      //radius: 4
      
  food_resources:
    title: "Food Resources"
    file: data/New_England_Food_Resources.geojson"
    type: "point"
    style:
      color: "#c9a0dc"
      radius: 4

  snap_vendors:
    title: "SNAP Vendors"
    file: "data/New_England_SNAP_Vendors.geojson"
    type: "point"
    style:
      color: "#1f78b4"
      radius: 4

  wic_vendors:
    title: "WIC Vendors"
    file: "data/New_England_WIC_Vendors.geojson"
    type: "point"
    style:
      color: "#e31a1c"
      radius: 4
