# Map configuration
initial_view:
  lat: 20
  lng: 0
  zoom: 3

# Layer definitions
layers:
  ME_WIC_Farmstands:
    title: "ME WIC Farmstands"
    file: "data/ME_WIC_Farmstands_wgs.geojson"
    type: "point"
    visible: true
    style:
      color: "#ff7800"
      radius: 8
      weight: 1
      opacity: 1
      fillOpacity: 0.8
      outlineColor: "#000"

  New_England_shelters:
    title: "New England shelters (privately run)"
    file: "data/New_England_shelters_privately_run_wgs.geojson"
    type: "point"
    visible: true
    style:
      color: "#1d5982"
      radius: 8
      weight: 1
      opacity: 1
      fillOpacity: 0.8
      outlineColor: "#000"

  New_England_SNAP_Vendors:
    title: "New England SNAP Vendors"
    file: "data/New_England_SNAP_Vendors_wgs.geojson"
    type: "point"
    visible: true
    style:
      color: "#835649"
      radius: 8
      weight: 1
      opacity: 1
      fillOpacity: 0.8
      outlineColor: "#000"

  New_England_WIC_Vendors:
    title: "New England WIC Vendors"
    file: "data/New_England_WIC_Vendors_wgs.geojson"
    type: "point"
    visible: true
    style:
      color: "#e81b2b"
      radius: 8
      weight: 1
      opacity: 1
      fillOpacity: 0.8
      outlineColor: "#000"
